name: password_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  animated_button: ^0.3.1
  sqflite_common_ffi: ^2.3.5
  sqlite3: ^2.7.6
  sqlcipher_flutter_libs: ^0.6.8
  fuzzywuzzy: ^1.2.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  googleapis: ^13.2.0
  oauth2: ^2.0.2
  url_launcher: ^6.3.1
  path: ^1.9.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
